name: CI

on:
    pull_request:
        branches:
            - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Bundler (ruby dependencies manager)
      run: sudo gem install bundler

    - name: Run tests
      run: make tests
